/**
 * @fileoverview AES-256-GCM symmetric encryption helpers for protecting
 * the bearer token stored in the in-memory cache.
 *
 * Why AES-256-GCM?
 *  - AES-256 is the current NIST standard for symmetric encryption.
 *  - GCM mode provides authenticated encryption: it produces an authentication
 *    tag that detects ciphertext tampering, so decrypt() returns null instead of
 *    silently returning garbage if someone modified the cached bytes.
 *  - Counter mode (CTR) inside GCM means there is no padding, so the ciphertext
 *    length equals the plaintext length (no block-size rounding).
 *
 * The encryption key is derived from the `VERTEIL_ENCRYPTION_KEY` environment
 * variable (32-byte hex string) or falls back to a randomly generated key
 * that persists only for the lifetime of the process.  For production use,
 * always supply a stable key via the environment variable.
 */

import crypto from 'crypto';

const ALGORITHM  = 'aes-256-gcm';
const IV_LENGTH  = 12;   // 96-bit IV — NIST recommends 96 bits (12 bytes) for GCM for performance
const TAG_LENGTH = 16;   // GCM authentication tag — 128 bits is the maximum and most secure length

/**
 * Derives or generates the 32-byte encryption key once per process.
 *
 * Key derivation order:
 *  1. `VERTEIL_ENCRYPTION_KEY` env var (hex string of 64 chars = 32 bytes) — stable across restarts
 *  2. `crypto.randomBytes(32)` cached on the function object — valid only for this process lifetime
 *
 * The ephemeral fallback (option 2) means tokens encrypted in one process run cannot be
 * decrypted by another process.  That is fine for the in-memory cache use case (the cache
 * itself is also per-process), but it means tokens are lost on restart.  Set
 * VERTEIL_ENCRYPTION_KEY in production to get a stable, restart-safe key.
 *
 * @returns {Buffer} 32-byte key.
 */
function getEncryptionKey() {
  const envKey = process.env.VERTEIL_ENCRYPTION_KEY;
  if (envKey) {
    const buf = Buffer.from(envKey, 'hex');
    // A 64-char hex string decodes to 32 bytes; validate length to catch misconfiguration early.
    if (buf.length !== 32) {
      throw new Error('VERTEIL_ENCRYPTION_KEY must be a 64-character hex string (32 bytes).');
    }
    return buf;
  }
  // Attach the generated key to the function object so it survives across multiple
  // encrypt()/decrypt() calls within the same process without being regenerated.
  if (!getEncryptionKey._cached) {
    getEncryptionKey._cached = crypto.randomBytes(32);
  }
  return getEncryptionKey._cached;
}

/**
 * Encrypts a UTF-8 plaintext string using AES-256-GCM.
 *
 * Wire format (all bytes concatenated before base64 encoding):
 *
 *   ┌──────────────────┬──────────────────────┬──────────────────────────┐
 *   │  IV  (12 bytes)  │  Auth tag (16 bytes)  │  Ciphertext (N bytes)    │
 *   └──────────────────┴──────────────────────┴──────────────────────────┘
 *
 * The IV (Initialisation Vector, also called nonce in GCM) must be unique per
 * encryption.  We generate a fresh random IV every call so that encrypting the
 * same token twice produces different ciphertext — this is a required property
 * of secure symmetric encryption (semantic security / IND-CPA).
 *
 * The auth tag is generated by GCM after encryption and must be stored alongside
 * the ciphertext.  During decryption, GCM recomputes the tag and compares it with
 * this stored value; if they differ, decryption fails (tampered data).
 *
 * @param {string} value Plaintext to encrypt.
 * @returns {string}     Base64-encoded bundle: IV + tag + ciphertext.
 * @throws {Error} If encryption fails.
 */
function encrypt(value) {
  const key    = getEncryptionKey();
  const iv     = crypto.randomBytes(IV_LENGTH);  // unique nonce per encryption
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);

  // cipher.update() processes the plaintext; cipher.final() flushes any remaining
  // buffered data (in GCM there is no padding so final() typically returns empty).
  const encrypted = Buffer.concat([
    cipher.update(value, 'utf8'),
    cipher.final(),
  ]);

  // getAuthTag() MUST be called after final() — only then has GCM computed the full tag.
  const tag = cipher.getAuthTag();

  // Pack IV + tag + ciphertext into a single Buffer and base64-encode for storage.
  return Buffer.concat([iv, tag, encrypted]).toString('base64');
}

/**
 * Decrypts a base64-encoded ciphertext that was produced by {@link encrypt}.
 *
 * Offsets for slicing the bundle:
 *   [0, 12)        → IV
 *   [12, 28)       → auth tag  (12 + 16 = 28)
 *   [28, end)      → ciphertext
 *
 * If the auth tag does not match (tampered data, wrong key, truncated buffer),
 * createDecipheriv's `final()` throws a `Bad tag` error, which we catch and
 * convert to a `null` return so the caller (SecureTokenStorage) treats it as
 * a missing token and triggers re-authentication.
 *
 * @param {string} encryptedValue Base64 ciphertext bundle.
 * @returns {string|null} Plaintext, or `null` on any decryption failure.
 */
function decrypt(encryptedValue) {
  try {
    const key = getEncryptionKey();
    const buf  = Buffer.from(encryptedValue, 'base64');

    // Slice the three components out of the packed buffer using the same fixed offsets
    // used during encrypt().  If the buffer is shorter than expected, subarray() returns
    // an empty buffer and decryption will fail at final(), which is handled below.
    const iv         = buf.subarray(0, IV_LENGTH);
    const tag        = buf.subarray(IV_LENGTH, IV_LENGTH + TAG_LENGTH);
    const ciphertext = buf.subarray(IV_LENGTH + TAG_LENGTH);

    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    // setAuthTag() must be called BEFORE update()/final() when decrypting.
    // It registers the expected tag so final() can verify it.
    decipher.setAuthTag(tag);

    return decipher.update(ciphertext, undefined, 'utf8') + decipher.final('utf8');
  } catch {
    // Any failure (wrong key, truncated data, tampered tag) returns null rather
    // than propagating an exception.  The caller treats null as "no valid token"
    // and will request a fresh one from the OAuth2 endpoint.
    return null;
  }
}

export { encrypt, decrypt };
